spring.application.name=composition-order

server.port=8091

#Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.swagger-ui.path=/swagger-ui

springdoc.pathsToMatch= /api/composition/**